# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\cesar\Downloads\Doc\IAProyecto1\MapaView\Views\Principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(777, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Mapa_Ruta = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Mapa_Ruta.setGeometry(QtCore.QRect(310, 410, 91, 21))
        self.pushButton_Mapa_Ruta.setObjectName("pushButton_Mapa_Ruta")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 651, 41))
        self.label.setObjectName("label")
        self.pushButton_Recibir_pedidos = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Recibir_pedidos.setGeometry(QtCore.QRect(40, 410, 221, 23))
        self.pushButton_Recibir_pedidos.setObjectName("pushButton_Recibir_pedidos")
        self.pushButton_Mapeo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Mapeo.setGeometry(QtCore.QRect(660, 410, 91, 21))
        self.pushButton_Mapeo.setObjectName("pushButton_Mapeo")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Mapa_Ruta.setText(_translate("MainWindow", "Mapa Ruta"))
        self.label.setText(_translate("MainWindow", "AQUI VA TU DESCR......"))
        self.pushButton_Recibir_pedidos.setText(_translate("MainWindow", "Recibir Pedidos y Generar Rutas"))
        self.pushButton_Mapeo.setText(_translate("MainWindow", "Mapeo"))
