# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\cesar\Downloads\Doc\IAProyecto1\MapaView\Views\Mapeo.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 549)
        self.Mapa = QtWidgets.QWidget(Form)
        self.Mapa.setGeometry(QtCore.QRect(20, 20, 601, 511))
        self.Mapa.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.Mapa.setObjectName("Mapa")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
